package com.ste.servlets;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.google.appengine.labs.repackaged.org.json.JSONObject;
import com.ste.beans.Servicio;
import com.ste.dao.ServicioDao;

public class ServicioServlet  extends HttpServlet{
	public void doGet(HttpServletRequest req, HttpServletResponse resp){

		JSONObject json = new JSONObject();
		
		String accion = req.getParameter("accion");
			
		 try {
			 
			HttpSession sesion = req.getSession();
			int sesionpermiso = (int) sesion.getAttribute("permiso");			 
			String usermail = (String) sesion.getAttribute("mail");
			

			
				if (accion.equals("inicial")){
					createServicio(req,resp,usermail);
				}


			
		} catch (Exception e) {

			e.printStackTrace();
		}		
	}
	
	public void doPost(HttpServletRequest req, HttpServletResponse resp){
		doGet(req,resp);
	}
	public void createServicio(HttpServletRequest req, HttpServletResponse resp, String usermail) throws InterruptedException{
		ServicioDao sDao = ServicioDao.getInstance();
		sDao.deleteAll();
		Servicio s = new Servicio();
		String nombre = "Adeudos B2B (Sepa) París       ";
		String tipo = "Envio";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		
		
		
		/*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
		/*-------------------------------------------------CODIGO GENERADO MEDIANTE REPLACE EN NOTEPAD++ PARA EXPORTAR DE EXCEL----------------------------------------------------*/
		/*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

		s = new Servicio();
		 nombre ="Adeudos Core (Sepa) París";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Adeudos directos 19.14 (Sepa)";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Adeudos directos 19.44 (Sepa B2B)   ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="AEB43           ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="C19.14 Cancelaciones/retrocesiones (Sepa)   ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="C19.44 Cancel/retroc. (Sepa B2B)     ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cancel./retr. B2b (Sepa) París";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cancel./retr. Core (Sepa) París           ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cesión de recibos domiciliados           ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cesiones de anticipos de crédito         ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cesiones de efectos al descuento        ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cesiones de pagos certificados           ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Cesiones de pagos domiciliados en fichero      ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Confirming de clientes ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Confirming en divisa    ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Devol.efectos descontados en fichero ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Devol.recibos en fichero         ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Devoluciones de antic.cred. Vía fichero          ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Emisión cheques en fichero 34.1";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Euroconfirming";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Factoring - remesas nuevas     ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impag. Adeud. Direct. (Sepa B2B)      ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impag. Cuaderno 19.44 (Sepa B2B)   ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impagados adeudos directos (Sepa)   ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impagados B2B (Sepa) París   ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impagados Core (Sepa) París  ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Impagados cuaderno 19.14 (Sepa)     ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Inf.pago imptos. Autonómicos en fichero        ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Inf.pago imptos. Municipales en fichero          ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Infor. Facturación comercios en fichero          ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Infor. Facturación comercios on line    ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Información recibos no domiciliados en fichero           ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mov. Tarj. Crédito en fichero fecha de liquidación      ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mt940";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mt942";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mvtos. Ctas.pers.fich.-etebac ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mvtos.tarjeta crédito en fichero          ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Mvtos.tarjeta cto en fich-altas automáticas      ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Nóminas 34.14           ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="OMF Banco de España en fichero      ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Órdenes de emisión de cheques          ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Órdenes de nomina vía fichero ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Órdenes de transferencia vía fichero     ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Órdenes nominas en fichero 34.1         ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Órdenes pago internacionales en fichero          ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pago internacionales - Bruselas            ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pago nóminas - París   ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pago proveedores - París        ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos (payment) - N.Y.          ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos chaps-tesorería mismo día Londres      ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos domésticos - Bruselas   ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos domésticos ach n.y.      ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos financieros - n.y.           ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos internacionales - París   ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos internacionales Londres";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos nacionales Londres       ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Pagos nóminas bacs Londres";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Rech. Adeud. Directos (Sepa B2B)     ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Rechazos adeudos directos (Sepa)     ";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Sepa - pagos Londres ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Sepa - pagos nóminas París    ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Sepa - pagos París      ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Transferencia 34.12    ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Transferencias 34.14   ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Transferencias tesorería - París           ";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio();
		 nombre ="Transferencias, en fichero 34.1";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);		
		
	}
	
}
