package com.ste.servlets;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.google.appengine.labs.repackaged.org.json.JSONObject;
import com.ste.beans.Servicio;
import com.ste.dao.ServicioDao;

public class ServicioServlet  extends HttpServlet{
	public void doGet(HttpServletRequest req, HttpServletResponse resp){

		JSONObject json = new JSONObject();
		
		String accion = req.getParameter("accion");
			
		 try {
			 
			HttpSession sesion = req.getSession();
			int sesionpermiso = (int) sesion.getAttribute("permiso");			 
			String usermail = (String) sesion.getAttribute("mail");
			

			
				if (accion.equals("inicial")){
					createServicio(req,resp,usermail);
				}


			
		} catch (Exception e) {

			e.printStackTrace();
		}		
	}
	
	public void doPost(HttpServletRequest req, HttpServletResponse resp){
		doGet(req,resp);
	}
	public void createServicio(HttpServletRequest req, HttpServletResponse resp, String usermail) throws InterruptedException{
		ServicioDao sDao = ServicioDao.getInstance();
		sDao.deleteAll();
		Servicio s = new Servicio();
		String nombre = "ADEUDOS B2B (SEPA) PARIS";
		String tipo = "Envio";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		
		
		
		/*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
		/*-------------------------------------------------CODIGO GENERADO MEDIANTE REPLACE EN NOTEPAD++ PARA EXPORTAR DE EXCEL----------------------------------------------------*/
		/*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
		
		s = new Servicio(); nombre = " ADEUDOS CORE (SEPA) PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ADEUDOS DIRECTOS 19.14 (SEPA)";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ADEUDOS DIRECTOS 19.44 (SEPA B2B)";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" AEB43";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" C19.14 CANCELACIONES/RETROCESIONES (SEPA)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" C19.44 CANCEL/RETROC. (SEPA B2B)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CANCEL./RETR. B2B (SEPA) PARIS";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CANCEL./RETR. CORE (SEPA) PARIS";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CESION DE RECIBOS DOMICILIADOS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CESIONES DE ANTICIPOS DE CREDITO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CESIONES DE EFECTOS AL DESCUENTO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CESIONES DE PAGOS CERTIFICADOS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CESIONES DE PAGOS DOMICILIADOS EN FICHERO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CONFIRMING DE CLIENTES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" CONFIRMING EN DIVISA";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" DEVOL.EFECTOS DESCONTADOS EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" DEVOL.RECIBOS EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" DEVOLUCIONES DE ANTIC.CRED.VIA FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" EMISION CHEQUES EN FICHERO 34.1";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" EUROCONFIRMING";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" FACTORING - REMESAS NUEVAS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAG. ADEUD. DIRECT. (SEPA B2B)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAG. CUADERNO 19.44 (SEPA B2B)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAGADOS ADEUDOS DIRECTOS (SEPA)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAGADOS B2B (SEPA) PARIS";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAGADOS CORE (SEPA) PARIS";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" IMPAGADOS CUADERNO 19.14 (SEPA)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" INF.PAGO IMPTOS. AUTONOMICOS EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" INF.PAGO IMPTOS.MUNICIPALES EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" INFOR. FACTURACION COMERCIOS EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" INFOR. FACTURACION COMERCIOS ON LINE";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" INFORMACION RECIBOS NO DOMICILIADOS EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MOV. TARJ. CREDITO EN FICHERO FECHA DE LIQUIDACION";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MT940";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MT942";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MVTOS. CTAS.PERS.FICH.-ETEBAC";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MVTOS.TARJETA CREDITO EN FICHERO";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" MVTOS.TARJETA CTO EN FICH-ALTAS AUTOMATICAS";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" NOMINAS 34.14";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" OMF BANCO DE ESPAÑA EN FICHERO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ORDENES DE EMISION DE CHEQUES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ORDENES DE NOMINA VIA FICHERO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ORDENES DE TRANSFERENCIA VIA FICHERO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ORDENES NOMINAS EN FICHERO 34.1";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" ORDENES PAGO INTERNACIONALES EN FICHERO";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGO INTERNACIONALES - BRUSELAS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGO NOMINAS - PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGO PROVEEDORES - PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS (PAYMENT) - N.Y.";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS CHAPS-TESORERIA MISMO DIA LONDRES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS DOMESTICOS - BRUSELAS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS DOMESTICOS ACH N.Y.";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS FINANCIEROS - N.Y.";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS INTERNACIONALES - PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS INTERNACIONALES LONDRES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS NACIONALES LONDRES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" PAGOS NOMINAS BACS LONDRES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" RECH. ADEUD. DIRECTOS (SEPA B2B)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" RECHAZOS ADEUDOS DIRECTOS (SEPA)";
		tipo = "Recepción";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" SEPA - PAGOS LONDRES";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" SEPA - PAGOS NOMINAS PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" SEPA - PAGOS PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" TRANSFERENCIA 34.12";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" TRANSFERENCIAS 34.14";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" TRANSFERENCIAS TESORERIA - PARIS";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail);
		s = new Servicio(); nombre =" TRANSFERENCIAS, EN FICHERO 34.1";
		tipo = "Envío";
		s.setNme(nombre);
		s.setTipo(tipo);
		sDao.createServicio(s, usermail); 
		
		
	}
	
}
